/**
 * @file:  ECE252/lab1/starter/ls/ls_ftype.c
 * @brief: Print the type of file for each command-line argument
 * @author: W. Richard Stevens, Advanced Programming in the UNIX Environment
 * @date: 2018/10/15
 */

#include <sys/types.h>      /* define data types used in system calls */
#include <sys/stat.h>       /* define `stat` structure and macros for determining file types */
#include <stdio.h>          /* provide functions for input and output, ex. `printf` `perror` */
#include <stdlib.h>         /* provide general utility functions, ex. `exit` */
#include <unistd.h>         /* provide access to the POSIX API, ex. `lstat` */

int main(int argc, char *argv[]) /* expect file or directory names as command line argument, 
                                    `argc`: argument count, # of command line arguments;
                                    `argv`: array of command line arguments */
{
    int i;
    char *ptr;
    struct stat buf;        /* a `stat` struct holds file info */

    for (i = 1; i < argc; i++) {        /* printing start at second element of array, since first one is the name of the program */
        printf("%s: ", argv[i]);        /* print file names and `:` */
        /* if `lstat()` fails (return -1),`perror()` print error message and move on to the next file */
        if (lstat(argv[i], &buf) < 0) {        
            perror("lstat error");
            continue;
        }   

        if      (S_ISREG(buf.st_mode))  ptr = "regular";
        else if (S_ISDIR(buf.st_mode))  ptr = "directory";
        else if (S_ISCHR(buf.st_mode))  ptr = "character special";
        else if (S_ISBLK(buf.st_mode))  ptr = "block special";
        else if (S_ISFIFO(buf.st_mode)) ptr = "fifo";
#ifdef S_ISLNK      /* conditionally include, because some systems may not support */
        else if (S_ISLNK(buf.st_mode))  ptr = "symbolic link";
#endif
#ifdef S_ISSOCK     /* conditionally include, because some systems may not support */
        else if (S_ISSOCK(buf.st_mode)) ptr = "socket";
#endif
        else                            ptr = "**unknown mode**";
        printf("%s\n", ptr);    /* print the file type and change a line */
    }
    return 0;
}

/* example generated by chatgpt
    example input: ./ls_ftype file.txt /dev/null /usr/bin /path/to/socket
    example output: file.txt: regular
                    /dev/null: character special
                    /usr/bin: directory
                    /path/to/socket: socket  */